### PR TITLE
Handles exception thrown by Firefox when calling getBBox within hidden element

### LINKED ISSUE #2692: [0.7.5+] NS_ERROR_FAILURE on Firefox 47
* **C3 version**: 0.7.5 and 0.7.6
* **D3 version**: 5.10.0
* **Browser**: Firefox 47.0.2
* **OS**: Linux

Updating from 0.7.4 to any of the two new versions causes `NS_ERROR_FAILURE` Exception, `result: 2147500037`. Not sure what that means. This is the stacktrace:

```
AxisInternal.prototype.updateTickTextCharSize/<@webpack://./node_modules/c3/src/axis-internal.js?:106:15
__webpack_exports__.default@webpack://./node_modules/d3-selection/src/selection/each.js?:5:28
AxisInternal.prototype.updateTickTextCharSize@webpack://./node_modules/c3/src/axis-internal.js?:103:3
axis/<@webpack://./node_modules/c3/src/axis-internal.js?:282:7
__webpack_exports__.default@webpack://./node_modules/d3-selection/src/selection/each.js?:5:28
axis@webpack://./node_modules/c3/src/axis-internal.js?:258:5
__webpack_exports__.default@webpack://./node_modules/d3-selection/src/selection/call.js?:5:3
redraw@webpack://./node_modules/c3/src/axis.js?:480:3
_chart_internal__WEBPACK_IMPORTED_MODULE_0__.ChartInternal.prototype.redraw@webpack://./node_modules/c3/src/core.js?:563:3
_chart_internal__WEBPACK_IMPORTED_MODULE_0__.ChartInternal.prototype.initWithData@webpack://./node_modules/c3/src/core.js?:327:5
_chart_internal__WEBPACK_IMPORTED_MODULE_0__.ChartInternal.prototype.init@webpack://./node_modules/c3/src/core.js?:59:5
Chart@webpack://./node_modules/c3/src/chart.js?:15:3
generate@webpack://./node_modules/c3/src/core.js?:36:12
```

Using the latest Chrome this doesn't happen so the issue is somewhere with older browsers.

### PR DESCRIPTION
**Pull request by panthony**
Before I made the change in #2672 I was not aware that Firefox threw an exception if the DOM element is not rendered (ex: display: none;).

This PR wraps every calls made to `getBBox` and returns an empty box instead.

The method `getBoundingClientRect` was returning an object with all properties set to 0.

Can't really add a test for this since this is FF specific and we only have a chrome runner

Closes #2692

### CODE REVIEW

File: src/util.js [hunk 1]
```diff
@@ -11,12 +11,26 @@ export var getOption = function(options, key, defaultValue) {
...
         minY = Math.min(items[0].y, items[1].y);
     return { x: minX, y: minY, width: box.width, height: box.height };
 };
+export var getBBox = function(element) {
+  try {
+      return element.getBBox();
+  } catch (ignore) {
+      // Firefox will throw an exception if getBBox() is called whereas the
+      // element is rendered with display:none
+      // See https://github.com/c3js/c3/issues/2692
```
Comment (kt3k) [inline src/util.js]: 👍
