### PR TITLE
correct DOMException when data name contains unicode

### LINKED ISSUE #2353: Uncaught DOMException when data label contains unicode
When a stacked area chart's group label contains unicode (`my\u007fapp`) this error occurs:

```
Uncaught DOMException: Failed to execute 'querySelectorAll' on 'Element': '.c3-selected-circles-my\u007fapp' is not a valid selector
```

* **C3 version**: 0.5.3
* **D3 version**: 4.13.0
* **Browser**: Chrome 66.0.3359.81
* **OS**: Mac OS X

### PR DESCRIPTION
**Pull request by panthony**
This PR closes #2353 

In the end I did not introduce a new dependency.

I though about #2407 where size really matters and I did not feel like adding this polyfill for everyone.

This PR uses `CSS.escape` or fallback to previous method if not available, meaning the issue would still occurs for old browsers (ex: IE) but I think we'd better off explaining this and leaving the responsability to the user to embed a polyfill if needed.

### CODE REVIEW

File: src/class-utils.js [hunk 1]
```diff
@@ -86,8 +86,13 @@ ChartInternal.prototype.classChartArc = function (d) {
...
 };
 ChartInternal.prototype.getTargetSelectorSuffix = function (targetId) {
-    return this.generateTargetClass(targetId)
-        .replace(/([?!@#$%^&*()_=+,.<>'":;\[\]\/|~`{}\\])/g, '\\$1');
+    const targetClass = this.generateTargetClass(targetId);
+    if (window.CSS && window.CSS.escape) {
+        return window.CSS.escape(targetClass);
+    }
+
+    // fallback on imperfect method for old browsers (does not handles unicode)
```
Comment (kt3k) [inline src/class-utils.js]: nice! 👍
